language: python
python:
- '3.6'
install:
- python -m setup install
script:
- python -m pytest -ra
deploy:
  script: python setup.py upload
  user: danybeam
  password:
    secure: p4S8IdeU1AEBrzRIyVxSX59kPfXgXbfQh3sNuzYibCMFbNTsrjSErZ9ZBtZbt5zfTn+IwpJ7tzQb5csi0FRpP6iEeKFWiMVsGg44Y8pSioCxvWe++c6QWbKtjJD2hQQJf6Q7M6k5ZSzVCWJfhu99eRqBcruZxB+09PWJQsf2RYJP3cY/mJUbvSNE/gI4olCSGik5aqzEucMwsjV+Z5499nCoM2hRY4LPFaZetP8LAzDEsaKXdms0L5iyMsPGjEyWyR1LwH9H2ph55mYWb28LTeMUQiwgmG+yrsc36c+GBuG9Povg1LXHoB8PDyTHd1DKWNEDLZ3jussLKJoWFaVtFYZzasZa3CgDKOrm+C+R/DyOTQuvKMffS8MR4bBlgYLMP5RY0/Ph91S9mmdtVcc0iKpx2KBC1aHLf43PHjpBtlYYvEzXEBCGwSbmJnIgVHohxd50h7IHD1oK5yzgkUf+rwicAIhBWBY8CsWfjD+pdzybko3AJJSr4kO4paSYiE741/SR2WR9zg7GykdvwZqEDs4fnkkQc3YMEIMnHNhmPA0wzduqOGow3/KkgE9PPRlKew+B9+l6ju0kJEJ3icDvZxTSxXdow8JbwQ/ATokdtcm/jsegMhOM7XR59aayub//QKmscXUY4kLMOr9lhNunxFqK4gOKTL/a1TEsWTD7h40=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ deploy"