language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python -m setup.py
before_deploy: "echo 'we need a script to push to deploy branch here'"
deploy:
  on:
    branch: release
